package com.D4vsus.numberRecognition.UI;

import com.D4vsus.numberRecognition.model.ImageToPredict;
import com.D4vsus.numberRecognition.network.AppBundle;
import com.D4vsus.numberRecognition.network.Client;
import com.D4vsus.numberRecognition.network.ServerListener;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import com.sun.tools.javac.Main;

import javax.swing.*;
import javax.swing.plaf.FontUIResource;
import javax.swing.text.StyleContext;
import java.awt.*;
import java.io.IOException;
import java.lang.reflect.Method;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * <h1>MainWindow</h1>
 * <p>Creates the window</p>
 *
 * @author D4vsus
 */
public class MainWindow extends JFrame {
    //variables and objects
    private JPanel mainWindow;
    private JPanel image;
    private JButton send;
    private JButton pencil;
    private JLabel number;
    private JButton restart;
    private JButton rubber;
    private JButton ip;
    private boolean isPencil;
    private Pixel[][] pixelBoard;
    private final Client client;

    //methods

    /**
     * <h1>Constructor</h1>
     * <p>Set up the window</p>
     */
    public MainWindow() {
        this.add(mainWindow);
        this.setTitle("MNIST");
        this.setBounds(50, 50, 1000, 1000);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(Main.class.getClassLoader().getResource("icon.png")));
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        setPencil();
        addImageBoard();

        restart.setMnemonic('r');
        send.setMnemonic('s');
        pencil.setMnemonic('p');
        rubber.setMnemonic('r');
        ip.setMnemonic('i');

        restart.addActionListener(e -> setAllBlack());
        send.addActionListener(e -> send());
        pencil.addActionListener(e -> setPencil());
        rubber.addActionListener(e -> setRubber());
        ip.addActionListener(e -> ip());

        client = new Client(new ServerListener() {
            @Override
            public void onConnect(String result) {
                MainWindow.this.number.setText(result);
            }

            @Override
            public void onFail(String result) {
                MainWindow.this.number.setText(result);
            }
        });

        this.setVisible(true);
    }

    /**
     * <h1>addImageBoard()</h1>
     * <p>Set up the white board to write</p>
     */
    private void addImageBoard() {
        pixelBoard = new Pixel[28][28];
        GridBagConstraints gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;

        for (int y = 0; y < pixelBoard.length; y++) {
            for (int x = 0; x < pixelBoard[y].length; x++) {
                pixelBoard[y][x] = new Pixel(() -> isPencil);
                image.add(pixelBoard[y][x].getPixelPanel(), gridBagConstraints);
                gridBagConstraints.gridx++;
            }
            gridBagConstraints.gridx = 0;
            gridBagConstraints.gridy++;
        }
    }

    /**
     * <h1>setAllBlack()</h1>
     * <p>set all the pixels to black</p>
     */
    private void setAllBlack() {
        for (Pixel[] pixels : pixelBoard) {
            for (Pixel pixel : pixels) {
                pixel.setBlack();
            }
        }
    }

    /**
     * <h1>setPencil()</h1>
     * <p>Activate the pencil</p>
     */
    private void setPencil() {
        isPencil = true;
        pencil.setEnabled(false);
        rubber.setEnabled(true);
    }

    /**
     * <h1>setRubber()</h1>
     * <p>Activate the Rubber</p>
     */
    private void setRubber() {
        isPencil = false;
        pencil.setEnabled(true);
        rubber.setEnabled(false);
    }

    /**
     * <h1>send()</h1>
     * <p>send the message to the server</p>
     */
    private void send() {
        try {
            Float[][] image = new Float[28][28];
            int y = 0;
            int x = 0;
            for (Pixel[] pixels : pixelBoard) {
                for (Pixel pixel : pixels) {
                    image[y][x] = (float) pixel.getColorNumber();
                    x++;
                }
                x = 0;
                y++;
            }

            ImageToPredict imageToPredict = new ImageToPredict();
            imageToPredict.setImage(image);

            client.send(imageToPredict);
        } catch (IOException e) {
            this.number.setText(AppBundle.getResourceBundle().getString("connection_error"));
        }
    }

    /**
     * <h1>ip()</h1>
     * <p>Open the dialog to set the Socket to comunicate</p>
     */
    private void ip() {
        new IPWindow();
        client.resetAPI();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainWindow = new JPanel();
        mainWindow.setLayout(new GridLayoutManager(3, 7, new Insets(0, 0, 0, 0), -1, -1));
        send = new JButton();
        send.setIcon(new ImageIcon(getClass().getResource("/AI.png")));
        send.setText("");
        send.setToolTipText(this.$$$getMessageFromBundle$$$("lang/lang", "button.send.ttt"));
        mainWindow.add(send, new GridConstraints(2, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        pencil = new JButton();
        pencil.setIcon(new ImageIcon(getClass().getResource("/pencil.png")));
        pencil.setText("");
        pencil.setToolTipText(this.$$$getMessageFromBundle$$$("lang/lang", "pencil.alt.p"));
        mainWindow.add(pencil, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        rubber = new JButton();
        rubber.setIcon(new ImageIcon(getClass().getResource("/rubber.png")));
        rubber.setText("");
        rubber.setToolTipText(this.$$$getMessageFromBundle$$$("lang/lang", "rubber.alt.r"));
        mainWindow.add(rubber, new GridConstraints(0, 2, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label1 = new JLabel();
        Font label1Font = this.$$$getFont$$$("Arial Black", Font.BOLD, 20, label1.getFont());
        if (label1Font != null) label1.setFont(label1Font);
        this.$$$loadLabelText$$$(label1, this.$$$getMessageFromBundle$$$("lang/lang", "label.your_number_is"));
        mainWindow.add(label1, new GridConstraints(2, 2, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        number = new JLabel();
        number.setEnabled(true);
        Font numberFont = this.$$$getFont$$$("Arial Black", Font.BOLD, 20, number.getFont());
        if (numberFont != null) number.setFont(numberFont);
        number.setText("");
        mainWindow.add(number, new GridConstraints(2, 3, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        restart = new JButton();
        restart.setIcon(new ImageIcon(getClass().getResource("/back.png")));
        restart.setText("");
        restart.setToolTipText(this.$$$getMessageFromBundle$$$("lang/lang", "clean.alt.r"));
        mainWindow.add(restart, new GridConstraints(0, 4, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        mainWindow.add(spacer1, new GridConstraints(0, 6, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final Spacer spacer2 = new Spacer();
        mainWindow.add(spacer2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JScrollPane scrollPane1 = new JScrollPane();
        mainWindow.add(scrollPane1, new GridConstraints(1, 1, 1, 4, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        image = new JPanel();
        image.setLayout(new GridBagLayout());
        scrollPane1.setViewportView(image);
        ip = new JButton();
        ip.setIcon(new ImageIcon(getClass().getResource("/ip.png")));
        ip.setText("");
        ip.setToolTipText(this.$$$getMessageFromBundle$$$("lang/lang", "ip.alt.i"));
        mainWindow.add(ip, new GridConstraints(0, 5, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        number.setLabelFor(scrollPane1);
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        Font font = new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
        boolean isMac = System.getProperty("os.name", "").toLowerCase(Locale.ENGLISH).startsWith("mac");
        Font fontWithFallback = isMac ? new Font(font.getFamily(), font.getStyle(), font.getSize()) : new StyleContext().getFont(font.getFamily(), font.getStyle(), font.getSize());
        return fontWithFallback instanceof FontUIResource ? fontWithFallback : new FontUIResource(fontWithFallback);
    }

    private static Method $$$cachedGetBundleMethod$$$ = null;

    private String $$$getMessageFromBundle$$$(String path, String key) {
        ResourceBundle bundle;
        try {
            Class<?> thisClass = this.getClass();
            if ($$$cachedGetBundleMethod$$$ == null) {
                Class<?> dynamicBundleClass = thisClass.getClassLoader().loadClass("com.intellij.DynamicBundle");
                $$$cachedGetBundleMethod$$$ = dynamicBundleClass.getMethod("getBundle", String.class, Class.class);
            }
            bundle = (ResourceBundle) $$$cachedGetBundleMethod$$$.invoke(null, path, thisClass);
        } catch (Exception e) {
            bundle = ResourceBundle.getBundle(path);
        }
        return bundle.getString(key);
    }

    /**
     * @noinspection ALL
     */
    private void $$$loadLabelText$$$(JLabel component, String text) {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++) {
            if (text.charAt(i) == '&') {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&') {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic) {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainWindow;
    }

}
