package com.D4vsus.numberRecognition.UI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.sun.tools.javac.Main;

import javax.swing.*;
import java.awt.*;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Objects;

/**
 * <h1>Pixel</h1>
 * <p>the minimum part of the model.image matrix</p>
 *
 * @author D4vsus
 */
public class Pixel {
    //variables and objects
    private JPanel pixel;
    private JLabel pixelColor;
    private int colorNumber;
    private final PixelChangeListener pixelChangeListener;

    //methods

    /**
     * <h1>Constructor</h1>
     * <p>Build the object</p>
     *
     * @param pixelChangeListener: {@link PixelChangeListener}
     */
    public Pixel(PixelChangeListener pixelChangeListener) {
        this.pixelChangeListener = pixelChangeListener;
        this.setBlack();
        this.pixelColor.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        this.pixelColor.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                whenClicking();
            }

            @Override
            public void mouseEntered(MouseEvent e) {
                if (SwingUtilities.isLeftMouseButton(e)) whenClicking();
            }

        });
    }

    /**
     * <h1>SetWhite()</h1>
     * <p>Set the pixel in white and set it's number to one</p>
     */
    public void setWhite() {
        this.colorNumber = 1;
        pixelColor.setIcon(new ImageIcon(Objects.requireNonNull(Main.class.getClassLoader().getResource("white.png"))));
    }

    /**
     * <h1>setBlack()</h1>
     * <p>Set the pixel in black and set it's number to cero</p>
     */
    public void setBlack() {
        this.colorNumber = 0;
        pixelColor.setIcon(new ImageIcon(Objects.requireNonNull(Main.class.getClassLoader().getResource("black.png"))));
    }

    /**
     * <h1>getColorNumber()</h1>
     * <p>Get the color number</p>
     *
     * @return int
     */
    public int getColorNumber() {
        return colorNumber;
    }

    /**
     * <h1>whenClicking()</h1>
     * <p>Activates when it's clicked switch the color of the pixel depending of the pencil or rubber</p>
     */
    public void whenClicking() {
        if (pixelChangeListener.onWrite()) setWhite();
        else setBlack();
    }

    /**
     * <h1>getPixelPanel()</h1>
     * <p>return the panel of the pixel</p>
     *
     * @return {@link  JPanel}
     */
    public JPanel getPixelPanel() {
        return pixel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pixel = new JPanel();
        pixel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        pixelColor = new JLabel();
        pixelColor.setIcon(new ImageIcon(getClass().getResource("/black.png")));
        pixelColor.setText("");
        pixel.add(pixelColor, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pixel;
    }
}
